java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryRequests: 2048Mi
  devcpuRequests: 2000m
  devmemoryLimits: 4096Mi
  devcpuLimits: 4000m
  environment:
    CREATE_CCD_ENDPOINT: true
    WORK_ALLOCATION_FEATURE: true
    CASE_ACCESS_MANAGEMENT_FEATURE: true
    SCHEDULE_LISTING_FEATURE: true
    TESTING_SUPPORT_ENABLED: true
