java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    CREATE_CCD_ENDPOINT: true
    WORK_ALLOCATION_FEATURE: true
    CASE_ACCESS_MANAGEMENT_FEATURE: true
    SCHEDULE_LISTING_FEATURE: true