version: "3.0"
services:
#  FIXME: because the ccd-data-store-api /health is not available this container cannot work.
# FIXME: Check with CCD team when they are going to update the docker images to solve this issue.
  tribunals-case-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/sscs/tribunals-case-api
    container_name: tribunals-case-api
    environment:
      IDAM_URL: http://localhost:4501
      IDAM_S2S-AUTH_TOTP_SECRET: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_S2S-AUTH_MICROSERVICE: sscs
      IDAM_S2S-AUTH: http://localhost:4502
      IDAM_SSCS_SYSTEMUPDATE_USER: SSCS_SYSTEM_UPDATE
      IDAM_SSCS_SYSTEMUPDATE_PASSWORD: SSCS_SYSTEM_UPDATE
      IDAM_OAUTH2_CLIENT_ID: sscs
      IDAM_OAUTH2_CLIENT_SECRET: QM5RQQ53LZFOSIXJ
      IDAM_SSCS_URL: https://localhost:9000/poc
      CORE_CASE_DATA_API_URL: http://localhost:4452
      CORE_CASE_DATA_JURISDICTION_ID: SSCS
      CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    ports:
      - 5000:8080
    depends_on:
      - service-auth-provider-api
      - ccd-data-store-api

  service-auth-provider-api:
      image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api:47e18b53aad48ae8124744041988565e07dfed50
      healthcheck:
        interval: 10s
        timeout: 10s
        retries: 10
      ports:
        - 4502:8080
      environment:
        auth.provider.service.server.jwtKey: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
        auth.provider.service.server.microserviceKeys.sscs: "${IDAM_KEY_CCD_GATEWAY}"
        auth.provider.service.testing-support.enabled: "true"


  ccd-data-store-api:
      image: "docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-api:${BRANCH:-master}"
      environment:
        DATA_STORE_DB_HOST: ccd-data-store-database
        DATA_STORE_DB_PORT: 5432
        DATA_STORE_DB_USERNAME:
        DATA_STORE_DB_PASSWORD:
        DATA_STORE_DB_USE_SSL:
        DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
        DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,sscs
        DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
        USER_PROFILE_HOST: http://ccd-user-profile-api:4453
        IDAM_USER_URL: http://idam-api:8080
        IDAM_S2S_URL: http://service-auth-provider-api:8080
        REFORM_SERVICE_NAME: ccd-data-store-api
        REFORM_TEAM: ccd
        REFORM_ENVIRONMENT: local
        APPINSIGHTS_INSTRUMENTATIONKEY: key
      ports:
        - 4452:4452
      depends_on:
        - ccd-data-store-database
        - ccd-user-profile-api
        - ccd-definition-store-api

  ccd-data-store-database:
      image: "docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-database:${BRANCH:-master}"
      healthcheck:
        interval: 10s
        timeout: 10s
        retries: 10
      environment:
        DATA_STORE_DB_USERNAME:
        DATA_STORE_DB_PASSWORD:
      ports:
        - 5452:5432
      volumes:
        - ccd-data-store-database-data:/var/lib/postgresql/data

  ccd-user-profile-api:
      image: "docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-api:${BRANCH:-master}"
      environment:
        USER_PROFILE_DB_HOST: ccd-user-profile-database
        USER_PROFILE_DB_PORT: 5432
        USER_PROFILE_DB_USERNAME:
        USER_PROFILE_DB_PASSWORD:
        USER_PROFILE_DB_USE_SSL:
        USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,sscs
        IDAM_S2S_URL: http://service-auth-provider-api:8080
        REFORM_SERVICE_NAME: ccd-user-profile-api
        REFORM_TEAM: ccd
        REFORM_ENVIRONMENT: local
        APPINSIGHTS_INSTRUMENTATIONKEY: key
      ports:
        - 4453:4453
      depends_on:
        - ccd-user-profile-database

  ccd-definition-store-api:
      image: "docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-api:${BRANCH:-master}"
      environment:
        DEFINITION_STORE_DB_HOST: ccd-definition-store-database
        DEFINITION_STORE_DB_PORT: 5432
        DEFINITION_STORE_DB_USERNAME:
        DEFINITION_STORE_DB_PASSWORD:
        DEFINITION_STORE_DB_USE_SSL:
        DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
        DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,sscs
        USER_PROFILE_HOST: http://ccd-user-profile-api:4453
        IDAM_USER_URL: http://idam-api:8080
        IDAM_S2S_URL: http://service-auth-provider-api:8080
        REFORM_SERVICE_NAME: ccd-definition-store-api
        REFORM_TEAM: ccd
        REFORM_ENVIRONMENT: local
        APPINSIGHTS_INSTRUMENTATIONKEY: key
      ports:
        - 4451:4451
      depends_on:
        - ccd-definition-store-database
        - ccd-user-profile-api

  ccd-definition-store-database:
      image: "docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-database:${BRANCH:-master}"
      healthcheck:
        interval: 10s
        timeout: 10s
        retries: 10
      environment:
        DEFINITION_STORE_DB_USERNAME:
        DEFINITION_STORE_DB_PASSWORD:
      ports:
        - 5451:5432
      volumes:
        - ccd-definition-store-database-data:/var/lib/postgresql/data

  ccd-user-profile-database:
      image: "docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-database:${BRANCH:-master}"
      healthcheck:
        interval: 10s
        timeout: 10s
        retries: 10
      environment:
        USER_PROFILE_DB_USERNAME:
        USER_PROFILE_DB_PASSWORD:
      ports:
        - 5453:5432
      volumes:
        - ccd-user-profile-database-data:/var/lib/postgresql/data

volumes:
  ccd-user-profile-database-data:
  ccd-definition-store-database-data:
  ccd-data-store-database-data:
