version: "3.0"
services:

  tribunals-case-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/tribunals-case-api
    environment:
      IDAM_URL: http://localhost:4501
      IDAM_S2S-AUTH_TOTP_SECRET: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_S2S-AUTH_MICROSERVICE: sscs
      IDAM_S2S-AUTH: http://localhost:4502
      IDAM_SSCS_SYSTEMUPDATE_USER: SSCS_SYSTEM_UPDATE
      IDAM_SSCS_SYSTEMUPDATE_PASSWORD: SSCS_SYSTEM_UPDATE
      IDAM_OAUTH2_CLIENT_ID: sscs
      IDAM_OAUTH2_CLIENT_SECRET: QM5RQQ53LZFOSIXJ
      IDAM_SSCS_URL: https://localhost:9000/poc
      CORE_CASE_DATA_API_URL: http://localhost:4452
      CORE_CASE_DATA_JURISDICTION_ID: SSCS
      CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    ports:
      - 8082:8080
