version: "3.0"
services:

  ccd-user-profile-api:
    image: hmcts/ccd-user-profile-api
    environment:
      USER_PROFILE_DB_HOST: ccd-user-profile-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME:
      USER_PROFILE_DB_PASSWORD:
      USER_PROFILE_DB_USE_SSL:
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,sscs
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - ccd-user-profile-database
    links:
      - ccd-user-profile-database
      - service-auth-provider-api

  ccd-user-profile-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      USER_PROFILE_DB_USERNAME:
      USER_PROFILE_DB_PASSWORD:
    ports:
      - 5453:5432
    volumes:
      - ccd-user-profile-database-data:/var/lib/postgresql/data

  ccd-definition-store-api:
    image: hmcts/ccd-definition-store-api
    environment:
      DEFINITION_STORE_DB_HOST: ccd-definition-store-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME:
      DEFINITION_STORE_DB_PASSWORD:
      DEFINITION_STORE_DB_USE_SSL:
      DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,sscs
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4451:4451
    depends_on:
      - ccd-definition-store-database
      - ccd-user-profile-api
    links:
      - ccd-definition-store-database
      - ccd-user-profile-api
      - idam-api
      - service-auth-provider-api

  ccd-definition-store-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DEFINITION_STORE_DB_USERNAME:
      DEFINITION_STORE_DB_PASSWORD:
    ports:
      - 5451:5432
    volumes:
      - ccd-definition-store-database-data:/var/lib/postgresql/data

  ccd-data-store-api:
    image: hmcts/ccd-data-store-api
    environment:
      DATA_STORE_DB_HOST: ccd-data-store-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME:
      DATA_STORE_DB_PASSWORD:
      DATA_STORE_DB_USE_SSL:
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,sscs
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4452:4452
    depends_on:
      - ccd-data-store-database
      - ccd-user-profile-api
      - ccd-definition-store-api
    links:
      - ccd-data-store-database
      - ccd-user-profile-api
      - ccd-definition-store-api
      - idam-api
      - service-auth-provider-api

  ccd-data-store-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DATA_STORE_DB_USERNAME:
      DATA_STORE_DB_PASSWORD:
    ports:
      - 5452:5432
    volumes:
      - ccd-data-store-database-data:/var/lib/postgresql/data

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      IDAM_SUPERUSER_EMAIL: ccd@hmcts.net
      SPRING_DATASOURCE_URL: jdbc:postgresql://idam-database:5432/idam
      SPRING_MAIL_HOST: smtp-server
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      NOTIFY_API_KEY: AAAAAAAAAAAAAAAA
      NOTIFY_CMC_ACTIVATE_USER_TEMPLATE: 76aa8695-64e8-4afd-ae13-bc8385302b1f
      IDAM_SECRET: idam_test_secret
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IDAM_CCD_WHITELIST: http://localhost:3451/oauth2redirect
      NOTIFY: "false"
      NOTIFY_CMC_WELCOME_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE: fake
      NOTIFY_SSCS_WELCOME_USER_TEMPLATE: fake
      NOTIFY_RESET_PASSWORD_TEMPLATE: "${NOTIFY_RESET_PASSWORD_TEMPLATE:fake}"
      NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_CCD_ACTIVATE_USER_TEMPLATE: fake
      REFORM_SERVICE_NAME: idam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
      http_proxy:
      https_proxy:
      no_proxy:
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_SSCS: QM5RQQ53LZFOSIXJ
      LOGGING_LEVEL_UK_GOV_HMCTS_IDAM: DEBUG
    ports:
      - 4501:8080
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server
  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database:latest
    ports:
      - 5501:5432
    volumes:
      - idam-database:/var/lib/postgresql/data

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      AUTH_PROVIDER_SERVICE_SERVER_JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      AUTH_PROVIDER_SERVICE_TESTING_SUPPORT_ENABLED: "true"
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_SSCS: "${IDAM_KEY_CCD_GATEWAY}"

  smtp-server:
    image: mailhog/mailhog
    ports:
      - 1025:1025

  pdf-service-api:
    image: docker.artifactory.reform.hmcts.net/reform/pdf-service-api
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - S2S_URL=http://service-auth-provider-api:8080
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME=pdf-service
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    ports:
      - 5500:5500
    healthcheck:
      retries: 40

  tribunals-case-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/tribunals-case-api
    environment:
      PDF_API_URL: http://pdf-service-api:5500
      IDAM_API_URL: http://idam-api:8080
      IDAM_S2S-AUTH_TOTP_SECRET: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_S2S-AUTH_MICROSERVICE: sscs
      IDAM_S2S-AUTH: http://service-auth-provider-api:8080
      IDAM_SSCS_SYSTEMUPDATE_USER: SSCS_SYSTEM_UPDATE
      IDAM_SSCS_SYSTEMUPDATE_PASSWORD: "${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:SSCS_SYSTEM_UPDATE}"
      IDAM_OAUTH2_CLIENT_ID: sscs
      IDAM_OAUTH2_CLIENT_SECRET: QM5RQQ53LZFOSIXJ
      IDAM_SSCS_URL: https://localhost:9000/poc
      CORE_CASE_DATA_API_URL: http://ccd-data-store-api:4452
      CORE_CASE_DATA_JURISDICTION_ID: SSCS
      CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    ports:
      - 8080:8080
    depends_on:
      - idam-api
      - service-auth-provider-api
      - pdf-service-api
      - smtp-server
      - ccd-data-store-api

volumes:
  ccd-user-profile-database-data:
  ccd-definition-store-database-data:
  ccd-data-store-database-data:
  idam-database:
