job:
  scheduler:
    autoStart: false
    retryPolicy:
      maxNumberOfJobExecutions: 2
      delayBetweenAttemptsInMs: 1000
    quartzProperties:
      org.quartz:
        scheduler:
          instanceId: AUTO
        jobStore:
          class: org.quartz.simpl.RAMJobStore