package uk.gov.hmcts.reform.sscs.ccd.presubmit.writefinaldecision.pip;

public enum PipTemplateComponentId {
    ALLOWED_OR_REFUSED_PARAGRAPH,
    CONFIRMED_OR_SET_ASIDE_PARAGRAPH,
    DAILY_LIVING_NO_AWARD_PARAGRAPH,
    MOBILITY_NO_AWARD_PARAGRAPH,
    DAILY_LIVING_DESCRIPTORS,
    MOBILITY_DESCRIPTORS,
    REASON,
    ANYTHING_ELSE,
    HEARING_TYPE,
    SUMMARY_OF_OUTCOME_DECISION,
    LIMITED_ABILITY_DAILY_LIVING_PARAGRAPH,
    IS_ENTITLED_DAILY_LIVING_PARAGRAPH,
    LIMITED_ABILITY_MOBILITY_PARAGRAPH,
    IS_ENTITLED_MOBILITY_PARAGRAPH;
}
