package uk.gov.hmcts.reform.sscs.ccd.presubmit.writefinaldecision.pip;

public enum PipTemplateComponentId {
    ALLOWED_OR_REFUSED_PARAGRAPH,
    CONFIRMED_OR_SET_ASIDE_PARAGRAPH,
    INSUFFICIENT_POINTS_PARAGRAPH,
    INSUFFICIENT_POINTS_PARAGRAPH_REGULATION_29_APPLIED,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_PARAGRAPH,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_RELATED_ACTIVITY_PARAGRAPH,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_REGULATION_35_APPLIED_PARAGRAPH,
    LIMITED_WORK_BUT_DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_PARAGRAPH,
    HAS_LIMITED_CAPABILITY_FOR_WORK,
    DISEASE_OR_DISABLEMENT_PARAGRAPH,
    SCHEDULE_2_DESCRIPTORS,
    DAILY_LIVING_DESCRIPTORS,
    MOBILITY_DESCRIPTORS,
    SCHEDULE_3_PARAGRAPH,
    SCHEDULE_3_DESCRIPTORS,
    REASON,
    ANYTHING_ELSE,
    HEARING_TYPE,
    SUMMARY_OF_OUTCOME_DECISION,
    RECOMMENDATION,
    LIMITED_ABILITY_DAILY_LIVING_PARAGRAPH,
    IS_ENTITLED_DAILY_LIVING_PARAGRAPH,
    LIMITED_ABILITY_MOBILITY_PARAGRAPH,
    IS_ENTITLED_MOBILITY_PARAGRAPH;

}
