package uk.gov.hmcts.reform.sscs.ccd.presubmit.writefinaldecision.pip;

public enum PipTemplateComponentId {
    DAILY_LIVING_NO_AWARD_PARAGRAPH,
    MOBILITY_NO_AWARD_PARAGRAPH,
    DAILY_LIVING_DESCRIPTORS,
    DAILY_LIVING_NOT_CONSIDERED_PARAGRPAH,
    MOBILITY_NOT_CONSIDERED_PARAGRPAH,
    MOBILITY_DESCRIPTORS,
    REASON,
    ANYTHING_ELSE,
    HEARING_TYPE,
    LIMITED_ABILITY_DAILY_LIVING_PARAGRAPH,
    IS_ENTITLED_DAILY_LIVING_PARAGRAPH,
    LIMITED_ABILITY_MOBILITY_PARAGRAPH,
    IS_ENTITLED_MOBILITY_PARAGRAPH;
}
