---
version: '3.5'

name: cft-lib-hearings-queue

services:
  active-mq:
    image: rmohr/activemq:latest
    ports:
      - 61616:61616
      - 8161:8161
      - 5672:5672
    networks:
      - cftlib_default

networks:
  cftlib_default:
    external: true
