package uk.gov.hmcts.reform.sscs.bulkscan;

public class TestDataConstants {

    private TestDataConstants() {
    }

    public static final String BENEFIT_TYPE = "PIP";
    public static final String BENEFIT_TYPE_DESCRIPTION = "Personal Independence Payment";
    public static final String MRN_DATE_VALUE = "01/11/2048";
    public static final String OFFICE = "5";
    public static final String DWP_REGIONAL_CENTRE = "Springburn";
    public static final String APPELLANT_TITLE = "Mr";
    public static final String APPELLANT_FIRST_NAME = "Henry";
    public static final String APPELLANT_LAST_NAME = "White";
    public static final String APPELLANT_ADDRESS_LINE1 = "10 My Road";
    public static final String APPELLANT_ADDRESS_LINE2 = "Hutton";
    public static final String APPELLANT_ADDRESS_LINE3 = "Brentwood";
    public static final String APPELLANT_ADDRESS_LINE4 = "Essex";
    public static final String APPELLANT_POSTCODE = "CM13 1BA";
    public static final String APPELLANT_ADDRESS_COUNTRY = "Iceland";
    public static final String APPELLANT_PORT_OF_ENTRY = "some-port-of-entry";
    public static final String APPELLANT_PHONE = "01234505050";
    public static final String APPELLANT_MOBILE = "07929292929";
    public static final String APPELLANT_EMAIL = "appellant@example.com";
    public static final String APPELLANT_DATE_OF_BIRTH = "12/08/1987";
    public static final String APPELLANT_NINO = "JT072319B";
    public static final String APPELLANT_IBCA_REFERENCE = "A12A12";
    public static final String APPELLANT_IBC_ROLE_FOR_SELF =  "myself";
    public static final String APPELLANT_IBC_ROLE_FOR_U18 =  "parent";
    public static final String APPELLANT_IBC_ROLE_FOR_LACKING_CAPACITY =  "guardian";
    public static final String APPELLANT_IBC_ROLE_FOR_POA =  "powerOfAttorney";
    public static final String APPELLANT_IBC_ROLE_FOR_DECEASED =  "deceasedRepresentative";
    public static final String APPOINTEE_TITLE = "Mrs";
    public static final String APPOINTEE_FIRST_NAME = "Wendy";
    public static final String APPOINTEE_LAST_NAME = "Baker";
    public static final String APPOINTEE_ADDRESS_LINE1 = "12 Acacia Avenue";
    public static final String APPOINTEE_ADDRESS_LINE2 = "The village";
    public static final String APPOINTEE_ADDRESS_LINE3 = "Romford";
    public static final String APPOINTEE_ADDRESS_LINE4 = "Essex";
    public static final String APPOINTEE_POSTCODE = "RM1 2KJ";
    public static final String APPOINTEE_DATE_OF_BIRTH = "03/12/1990";
    public static final String APPOINTEE_PHONE = "01874505050";
    public static final String APPOINTEE_MOBILE = "07929295555";
    public static final String APPOINTEE_COMPANY = "Monsters Inc";
    public static final String REPRESENTATIVE_NAME = "IBM";
    public static final String REPRESENTATIVE_ADDRESS_LINE1 = "63 Grovehill Road";
    public static final String REPRESENTATIVE_ADDRESS_LINE2 = "The Square";
    public static final String REPRESENTATIVE_ADDRESS_LINE3 = "Redhill";
    public static final String REPRESENTATIVE_ADDRESS_LINE4 = "Surrey";
    public static final String REPRESENTATIVE_POSTCODE = "RH1 4TR";
    public static final String REPRESENTATIVE_PHONE_NUMBER = "01540 234050";
    public static final String REPRESENTATIVE_EMAIL = "rep@example.com";
    public static final String REPRESENTATIVE_PERSON_TITLE = "Mr";
    public static final String REPRESENTATIVE_PERSON_FIRST_NAME = "David";
    public static final String REPRESENTATIVE_PERSON_LAST_NAME = "North";
    public static final String CHILD_MAINTENANCE_NUMBER = "Test1234";
    public static final String OTHER_PARTY_TITLE = "Mrs";
    public static final String OTHER_PARTY_FIRST_NAME = "Wendy";
    public static final String OTHER_PARTY_LAST_NAME = "Fisher";
    public static final String OTHER_PARTY_ADDRESS_LINE1 = "299 Harrow";
    public static final String OTHER_PARTY_ADDRESS_LINE2 = "The Avenue";
    public static final String OTHER_PARTY_ADDRESS_LINE3 = "Hatch End";
    public static final String OTHER_PARTY_POSTCODE = "HA5 4QT";
    public static final String APPEAL_LATE_REASON = "On holiday";
    public static final String APPEAL_REASON = "This is the reason of the appeal";
    public static final String IS_HEARING_TYPE_ORAL = "true";
    public static final String IS_HEARING_TYPE_PAPER = "false";
    public static final String HEARING_OPTIONS_EXCLUDE_DATES = "01/12/2030";
    public static final Boolean HEARING_LOOP = true;
    public static final Boolean SIGN_LANGUAGE_REQUIRED = true;
    public static final String SIGN_LANGUAGE_TYPE = "My sign language";
    public static final String HEARING_OPTIONS_LANGUAGE_TYPE = "Spanish";
    public static final String HEARING_OPTIONS_DIALECT_TYPE = "Castilian";
    public static final Boolean AGREE_LESS_HEARING_NOTICE = true;
    public static final String SIGNATURE_NAME = "Barry Smith";
    public static final String BENEFIT_CODE = "002";
    public static final String ISSUE_CODE = "DD";
    public static final String CASE_CODE = "002DD";
    public static final String HEARING_TELEPHONE_NUMBER = "01234567890";
    public static final String HEARING_VIDEO_EMAIL = "my@email.com";
    public static final String OTHER_PARTY_ID_ONE = "1";
    public static final String PROCESSING_VENUE = "Cardiff";
    public static final String EPIMMS_ID = "1";
    public static final String REGION_ID = "100";
    public static final String VENUE_POSTCODE = "CF24 0AB";
    public static final String SSCS8_FORM_TYPE = "sscs8";
}
