package uk.gov.hmcts.reform.sscs.ccd.presubmit.writefinaldecision.uc.scenarios;

public enum UcTemplateComponentId {
    INSUFFICIENT_POINTS_PARAGRAPH,
    INSUFFICIENT_POINTS_PARAGRAPH_SCHEDULE_8_PARAGRAPH_4_APPLIED,
    DOES_HAVE_LIMITED_CAPABILITY_FOR_WORK_PARAGRAPH,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_RELATED_ACTIVITY_PARAGRAPH,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_SCHEDULE_9_PARAGRAPH_4_APPLIED_PARAGRAPH,
    LIMITED_WORK_BUT_DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_PARAGRAPH,
    HAS_LIMITED_CAPABILITY_FOR_WORK,
    DISEASE_OR_DISABLEMENT_PARAGRAPH,
    SCHEDULE_6_DESCRIPTORS,
    SCHEDULE_7_PARAGRAPH,
    SCHEDULE_7_DESCRIPTORS;
}
