package uk.gov.hmcts.reform.sscs.ccd.presubmit.writefinaldecision.esa.scenarios;

public enum EsaTemplateComponentId {
    INSUFFICIENT_POINTS_PARAGRAPH,
    INSUFFICIENT_POINTS_PARAGRAPH_REGULATION_29_APPLIED,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_PARAGRAPH,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_RELATED_ACTIVITY_PARAGRAPH,
    DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_REGULATION_35_APPLIED_PARAGRAPH,
    LIMITED_WORK_BUT_DOES_NOT_HAVE_LIMITED_CAPABILITY_FOR_WORK_PARAGRAPH,
    HAS_LIMITED_CAPABILITY_FOR_WORK,
    DISEASE_OR_DISABLEMENT_PARAGRAPH,
    SCHEDULE_2_DESCRIPTORS,
    SCHEDULE_3_PARAGRAPH,
    SCHEDULE_3_DESCRIPTORS;
}
